<?php
$AddToCartIsActive = Mage::getStoreConfig("otimizar_facebookpixel/events/add_to_cart");
if($AddToCartIsActive):
    $_product = Mage::getModel('core/session')->getData('ProductToShoppingCart') ?>
    <?php 
    if (!empty($_product) && $_product->getId()){
	    $price = $_product->getData("special_price");
	    if(!$price){$price = $_product->getPrice();}
	    $price = number_format($price,2,".","");
	    $currency = Mage::app()->getStore()->getCurrentCurrencyCode();
	    ?>
	    <script type="text/javascript">
            <?php echo Mage::getStoreConfig("otimizar_facebookpixel/general/fbq_checker");?>
            fbq.push('track', 'AddToCart', {
	            content_ids: ['<?php echo $_product->getSku();?>'],
	            content_type: 'product',
	            value: <?php echo $price;?>,
	            currency:  <?php echo $currency;?>
	        });
	    </script>
	    <?php
        Mage::getModel('core/session')->setData('ProductToShoppingCart','');
    }
	?>
    <?php
endif;
?>